apiVersion: v1
kind: Service
metadata:
  name: backend-java
  namespace: cicd-demo
  labels:
    app: backend-java
spec:
  selector:
    app: backend-java
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
