apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test-deployment
  namespace: appdu-demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
        - name: java-test
          image: image-registry.openshift-image-registry.svc:5000/appdu-demo4/java-test
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          envFrom:
          - configMapRef:
              name: java-test-configmap
          - secretRef:
              name: java-test-secret
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
