apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
  namespace: edu1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      containers:
        - name: backend-java
          image: image-registry.openshift-image-registry.svc:5000/appdu-demo4/java-test
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 300
            timeoutSeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
