apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
  namespace: edu1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-test
  template:
    metadata:
      labels:
        app: java-test
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
        - name: backend-java
          image: ictcoe.azurecr.io/backend-java:master-20240712051613
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
