apiVersion: v1
kind: Ingress
metadata:
  name: frontend-vue
  namespace: edu1
spec:
  ingressClassName: nginx
  rules:
    - host: frontend-vue.52.231.144.33.nip.io
      http:
        paths:
        - backend:
            service:
              name: frontend-vue
              port:
                name: http
          path: /
          pathType: Prefix
