name: Publish Frontend-Vue Docker Azure image

on:      
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "master"
    
jobs:
  push_to_registry:
    name: Push Docker image to Azure ACR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: edu1-gitops-dev/frontend-vue/jenkins/Dockerfile
          push: true
          tags: ${{ secrets.AZURE_URL }}/frontend-vue:${{ github.event.inputs.name }}-${{ github.sha }}
